on: 
  push:
  workflow_dispatch: 

name: Dead code analysis

jobs:
  deadnix:
    name: Deadnix
    runs-on: ubuntu-latest

    steps:
      # リポジトリをチェックアウト
      - uses: actions/checkout@v4

      - uses: nixbuild/nix-quick-install-action@v30
        with:
         nix_conf: |
          keep-env-derivations = true
          keep-outputs = true

      # Cachix を「ダウンロード専用（pull only）」で使用
      # authToken を指定しないので push はしない
      - uses: cachix/cachix-action@v15
        with:
          name: deadnix

      # GitHub Actions のキャッシュで /nix/store を再利用
      - uses: nix-community/cache-nix-action@v6
        with:
          # OS + nix式 + flake.lock が完全一致したらヒット
          primary-key: nix-deadnix-${{ runner.os }}-${{ hashFiles('**/*.nix') }}
          restore-prefixes-first-match: nix-deadnix-${{ runner.os }}-
          gc-max-store-size-linux: 3G

      # deadnix 実行（未使用コード解析）
      - uses: astro/deadnix-action@main
        with:
          create_pr: true
          flags: "--edit --exclude=./_sources"
